const serviceCategories = {
  architects: [
    "Fundamental design concepts (for generating quotes and presenting planning applications)",
    "Detailed compliant blueprints (for builders and building regulations)",
    "Building structure calculations",
    "Not sure",
  ],
  bathroom: [
    "Bathroom refurbishment / installation",
    "Install or replace a fixture",
    "Repair",
    "Tiling",
    "Other",
  ],
  bricklayingRepointing: [
    "Building a wall",
    "Building a structure",
    "Building custom brickwork",
    "Wall alterations",
    "Repointing",
    "Chimney work",
    "Repairs",
  ],
  carpentryJoinery: [
    "Doors, windows & floors",
    "Furniture making, assembly & repairs",
    "Kitchen units & worktops",
    "Decking",
    "Other carpentry work",
  ],
  carpetsLinoFlooring: [
    "New or replacement flooring",
    "Sanding / Restoration",
    "Repair / Adjustment",
    "Other",
  ],
  centralHeating: [
    "Boiler",
    "Pipework / supply",
    "Radiators",
    "Thermostat",
    "Underfloor heating",
    "Full system installation",
    "Other",
  ],
  chimneyFireplace: [
    "Chimney",
    "Fireplace",
    "Flue",
    "Other or several of the above",
  ],
  conservatories: [
    "A new conservatory installation",
    "Replace or improve an existing conservatory",
    "A repair",
  ],
  dampProofing: [
    "No - I need help investigating",
    "Yes - I just need help fixing the problem",
  ],
  demolitionClearance: [
    "Waste removal only",
    "Building / structure demolition",
    "Knock down a wall",
  ],
  drivewaysPaving: [
    "Install a driveway",
    "Clean or reseal a driveway",
    "Dropped kerb (crossover)",
    "Paving, patios and paths",
  ],
  electrical: [
    "Rewiring",
    "Fuseboxes",
    "Electrical fittings & appliances",
    "Safety check or certificate",
    "Electrical faults & repairs",
    "Other",
  ],
  extensions: [
    "Property extension",
    "Loft conversion",
    "A porch",
    "Outbuilding",
    "Internal alterations",
    "Other",
  ],
  fasciasSoffitsGuttering: [
    "Guttering only",
    "Fascias and/or soffits only",
    "Both",
  ],
  fencing: ["Fencing", "Gates", "Fencing and gates", "Repair a fence or gate"],
  gardeningLandscaping: ["General gardening", "Landscaping", "Tree Surgery"],
  gasWork: [
    "Gas safety check",
    "Service boiler or appliance",
    "Install or replace boiler or appliance",
    "Move or remove boiler or appliance",
    "Pipework only",
    "Problem or repair",
    "Other",
  ],
  groundworkFoundations: [
    "Foundations for a structure to be built",
    "Drainage & pipework",
    "General garden earthworks",
    "Other",
  ],
  handymanCategory: [
    "The job include eletrical work",
    "The job does not include eletrical work",
  ],
  insulationCategory: [
    "Loft / roof insulation",
    "Wall insulation",
    "Floor insulation",
    "Other",
  ],
  kitchenFittingCategory: [
    "New kitchen installation",
    "Worktop installation",
    "Cabinet door refurbishment / replacement",
    "Fit appliance (sink, oven, dishwasher, etc.)",
    "Minor repair",
    "Several of the above, or other",
  ],
  locksmithCategory: [
    "Install new locks",
    "Repair locks",
    "Other (e.g. locked out)",
  ],
  loftConversionsCategory: [
    "Loft conversion with structural changes",
    "Loft conversion (no structural changes)",
    "Loft conversion for storage purposes",
    "Fit a skylight",
  ],
  newBuildCategory: [
    "I own the land I plan to build on",
    "I`m purchasing the land I plan to build on",
    "I don`t own the land I plan to build on",
  ],
  paintingDecoratingCategory: ["Inside painting", "Outside painting", "Both"],
  plasteringRenderingCategory: ["Plastering (indoors)", "Rendering (outdoors)"],
  plumbingCategory: [
    "Radiators",
    "Boilers",
    "Appliances",
    "Fixtures",
    "Pipework, taps & drainage",
  ],
  restorationRefurbishmentCategory: [
    "I understand that This trade is for large jobs that require management and oversight. If you require multiple jobs that cover various trades, please post these separately in the appropriate trade categories.",
  ],
  roofingCategory: [
    "New or replacement roof",
    "Roof repair or assessment",
    "Chimney work",
    "Something else",
  ],
  securitySystems: [
    "Security alarm system",
    "CCTV/Smart camera",
    "Entry system",
    "Smoke alarms",
    "Security lights",
    "Locks",
    "Other",
  ],
  stonemasonryCategory: ["Building", "Repairing", "Repointing", "Other"],
  tillingCategory: [
    "New or replacement tiles",
    "Repair / regrout tiles",
    "Other",
  ],
  treeSurgeryCategory: [
    "Trimming or topping",
    "Cutting down (felling)",
    "Stump removal only",
    "Diagnosis / Assessment",
    "Bushes, or other gardening tasks",
    "Other",
  ],
  windowsDoorFitingCategory: [
    "New windows",
    "New doors (internal or external)",
    "New windows and external doors",
    "Replace glass",
    "Repair",
    "Other",
  ],
};
export default serviceCategories;
